package ru.accept_applicant_documents.system.enums;

public enum Faculties {
    FACULTY_OF_BIOLOGY,
    FACULTY_OF_THEOLOGY,
    FACULTY_OF_GEOGRAPHY,
    FACULTY_OF_GEOLOGY,
    FACULTY_OF_JOURNALISM,
    FACULTY_OF_INFORMATION,
    FACULTY_OF_HISTORY,
    FACULTY_OF_CYBERNETICS,
    FACULTY_OF_MATHEMATICS,
    FACULTY_OF_MECHANICS,
    FACULTY_OF_POLITICAL_SCIENCE,
    FACULTY_OF_PSYCHOLOGY,
    FACULTY_OF_RADIO_ENGINEERING,
    FACULTY_OF_SOCIOLOGY,
    FACULTY_OF_MANAGEMENT,
    FACULTY_OF_PHYSICS,
    FACULTY_OF_PHILOLOGY,
    FACULTY_OF_PHILOSOPHY,
    FACULTY_OF_CHEMISTRY,
    FACULTY_OF_ART_AND_GRAPHICS,
    FACULTY_OF_ECONOMICS,
    FACULTY_OF_ELECTRONICS,
    FACULTY_OF_LAW

}
