package ru.accept_applicant_documents.system.enums;

public enum Specializations {

    PHYSICO_CHEMICAL_BIOLOGY,
    GENERAL_BIOLOGY,
    ECOLOGY_AND_NATURE_MANAGEMENT,


    THEOLOGY,
    RELIGIOUS_STUDIES,
    PHILOLOGY,
    SOCIAL_WORK,


    GEOGRAPHY,
    CARTOGRAPHY_AND_GEOINFORMATICS,
    HYDROMETEOROLOGY,
    TOURISM,


    GEOLOGY_AND_MINERALS,
    GEOPHYSICS,
    GEOCHEMISTRY,
    GEOLOGY_AND_GEOCHEMISTRY_OF_FOSSIL_FUELS,
    HYDROGEOLOGY_ENGINEER_GEOLOGY_GEOCRYOLOGY,
    ECOLOGICAL_GEOLOGY,


    JOURNALISM,
    INTERNATIONAL_JOURNALISM,
    MULTIMEDIA_JOURNALISM,
    PERIODICAL_PRINTING,
    TELEVISION_JOURNALISM,
    INTERNET_JOURNALISM,
    BUSINESS_JOURNALISM,
    POLITICAL_JOURNALISM,


    COMPUTER_SCIENCE_AND_ENGINEERING,
    APPLIED_COMPUTER_SCIENCE,
    SOFTWARE_ENGINEERING,
    INFORMATION_SECURITY,
    INSTRUMENT_ENGINEERING,
    INNOVATIKA,
    BUSINESS_INFORMATICS,


    HISTORY,
    DOCUMENTATION_MANAGEMENT,
    MUSEUM_BUSINESS_AND_PROTECTION_OF_HISTORICAL_AND_CULTURAL_HERITAGE,
    HISTORICAL_AND_ARCHIVAL_STUDIES,
    REGIONAL_STUDIES,
    ANTHROPOLOGY_AND_ETHNOLOGY,


    AUTOMATION_OF_TECHNOLOGICAL_PROCESSES_AND_PRODUCTIONS,
    AUTOMATED_INFORMATION_PROCESSING_AND_MANAGEMENT_SYSTEMS,
    VEHICLE_SERVICE,


    FUNDAMENTAL_MATHEMATICS,
    MATHEMATICAL_METHODS_OF_ECONOMICS,
    MATHEMATICS_AND_ECONOMIC_THEORY,
    APPLIED_MATHEMATICS_AND_COMPUTER_SCIENCE,
    MATHEMATICS_AND_COMPUTER_SCIENCE,
    SPACE_RESEARCH_AND_COSMONAUTICS,


    MECHANICS,
    MECHANICAL_ENGINEERING,
    TECHNOLOGICAL_MACHINE_AND_EQUIPMENT,
    MECHATRONICS_AND_ROBOTICS,


    STRATEGIC_MANAGEMENT_OF_ECONOMIC_AND_POLITICAL_PROCESSES,
    GENERAL_POLITICAL_SCIENCE,
    POLITICAL_MANAGEMENT_IN_PUBLIC_RELATIONS,
    PUBLIC_POLICY_AND_MANAGEMENT,
    POLITICAL_TECHNOLOGIES,
    WORLD_POLITICS,


    PSYCHOLOGICAL_AND_PEDAGOGICAL_EDUCATION,
    DEFECTOLOGICAL_EDUCATION,
    PSYCHOLOGY,
    CLINICAL_PSYCHOLOGY,
    THE_PSYCHOLOGY_OF_OFFICE_WORK,
    PEDAGOGY_AND_PSYCHOLOGY_OF_DEVIANT_BEHAVIOR,


    RADIO_ENGINEERING,
    DESIGN_AND_TECHNOLOGY_OF_ELECTRONIC_DEVICES,
    ELECTRONICS_AND_NANOTECHNOLOGY,
    NANOENGINEERING,
    INFOCOMMUNICATION_TECHNOLOGIES_AND_COMMUNICATION_SYSTEMS,


    APPLIED_COMPUTER_SCIENCE_IN_SOCIOLOGY,
    SOCIOLOGY_OF_MANAGEMENT,
    SOCIOLOGY_OF_BUSINESS,
    ECONOMIC_SOCIOLOGY,
    SOCIOLOGY_OF_LAW,
    SOCIOLOGY_OF_RELIGION,
    SOCIOLOGY_OF_CULTURE,
    SOCIOLOGY_OF_PERSONALITY,
    MILITARY_SOCIOLOGY,
    FAMILY_SOCIOLOGY,


    STATE_AND_MUNICIPAL_ADMINISTRATION,
    PERSONNEL_MANAGEMENT,
    ORGANIZATION_MANAGEMENT,
    PRODUCTION_MANAGEMENT,
    PROJECT_MANAGEMENT,
    FINANCIAL_MANAGEMENT,


    APPLIED_MATHEMATICS_AND_PHYSICS,
    PHYSICAL_COMPUTER_SCIENCE,
    GENERAL_AND_FUNDAMENTAL_PHYSICS,
    ASTRONOMY,
    RADIOPHYSICS,
    NANOTECHNOLOGY_AND_MICROSYSTEM_ENGINEERING,


    CLASSICAL_PHILOLOGY,
    GENERAL_LINGUISTICS,
    COMMUNICATION_STUDIES,
    LITERARY_STUDIES,
    APPLIED_LINGUISTICS,
    TEACHER_OF_RUSSIAN_LANGUAGE_AND_LITERATURE,
    COPYWRITER,
    PUBLISHING_BUSINESS,
    ROMANO_GERMAN_SEPARATION,
    ORIENTAL_LANGUAGES,
    PSYCHOLINGUISTICS,
    MODERN_MEDIA_COMMUNICATIONS,


    PHILOSOPHY,
    PUBLIC_RELATIONS_ADVERTISING,
    CULTURAL_STUDIES,


    BIOTECHNOLOGY,
    PHARMACY,
    FUNDAMENTA_AND_APPLIED_CHEMISTRY,
    CHEMICAL_TECHNOLOGY,
    TECHNOSPHERE_SAFETY,
    DEVELOPMENT_OF_BIOPHARMACEUTICALS,
    ANALYTICAL_CHEMISTRY,
    ORGANIC_CHEMISTRY,


    PAINTING,
    GRAPHICS,
    SCULPTURE,
    DESIGN,
    DECORATIVE_AND_APPLIED_ARTS_AND_FOLK_CRAFTS,
    GRAPHIC_DESIGN,
    ILLUSTRATOR,
    _3D_MODELER,
    INTERIOR_DESIGNER,
    TEACHER_OF_FINE_ARTS,
    PRODUCTION_DESIGNER,
    RESTORER,


    ECONOMICS_AND_MANAGEMENT,
    FINANCE_AND_CREDIT,
    INTERNATIONAL_ECONOMICS,
    ACCOUNTING_AND_AUDITING,
    ECONOMIC_SECURITY,


    RADIO_ELECTRONIC_SYSTEMS_AND_COMPLEXES,
    LASER_TECHNOLOGY_AND_LASER_TECHNOLOGY,
    ELECTRONICS_AND_AUTOMATION_OF_PHYSICAL_INSTALLATIONS,
    ELECTRONIC_AND_OPTOELECTRONIC_DEVICES_IN_A_SPECIAL_PURPOSE_SYSTEM,


    CIVIL_LAW,
    JURISPRUDENCE,
    CRIMINAL_LAW,
    NATURAL_RESOURCE_AGRARIAN_AND_ENVIRONMENTAL_LAW,
    STATE_LAW,
    THEORY_AND_HISTORY_OF_THE_STATE_AND_LAW,
    LAW_AND_ECONOMICS

}
